### PR TITLE
I added functionality to save as json files with domain names.

### PR DESCRIPTION
**Pull request by cagriaslan**
I also didn't touch the part that you output the json. But it looks obsolete now.

### CODE REVIEW

**Comment by narbehaj** [comment]
Great thanks, how about adding an argument for saving to JSON file? There are times that some users want to only pipe the JSON to another tool and not only save them.

**Comment by cagriaslan** [comment]
That makes sense! I needed the way I did so I didn't think deep into this. Will do when I have the chance.

**Comment by narbehaj** [comment]
It's okay, I'll add it today. 
Thanks for the PR :)

**Comment by cagriaslan** [comment]
You are welcome. Thanks for the tool.

**Comment by cagriaslan** [comment]
Oops there seems to be a bug because it saves all json output into all files. All of the files exported is the same and contains all jsons. This is to happen when multiple domains are feeded.

**Comment by narbehaj** [comment]
Ok let me look into it

**Comment by narbehaj** [comment]
Pull the latest commit. Fixed. Thanks.

**Pull request merged**
