### PR TITLE
Days left

### PR DESCRIPTION
**Pull request by jpmens**
Add `days_left` to context indicating how many days remain until certificate expiration. I think this would be practical in the context of monitoring.

### CODE REVIEW

**Comment by narbehaj** [comment]
Don't we have this in the context? I have already put it in `Valid to` section:
```
		Valid to: 2020-02-04 (65 days left)
```

**Comment by jpmens** [comment]
I see `"valid_till": "2019-12-26"` which is a date.

**Comment by jpmens** [comment]
You're right: the plain output has `Valid to: 2020-01-28 (58 days left)`, but the JSON doesn't.

**Comment by narbehaj** [comment]
It's in the JSON, check the `validity_days` key. Let me know if this is ok.

**Comment by jpmens** [comment]
`validity_days": 90` is the validity of the certificate as issued (from .. to). For all Let's Encrypt certificates I've tested it is 90 days. That is not what I need.

```
$ ../ssl_checker.py -jp -H google.de | grep validity_days
        "validity_days": 84,

$ ./ssl_checker.py -H google.de | grep 'Valid to'
		Valid to: 2020-01-28 (58 days left)
```

Note how 84 != 58.

The PR provides for "days until the certificate expires" begining now. I do not see that value in the current JSON.

**Comment by narbehaj** [comment]
Got it, thanks.

**Pull request merged**
